### ISSUE TITLE
Not possible to view "users page"

### ISSUE THREAD

**Issue by PWE-ASD** [martin-denizet/wiking#2]
I installed the plugin and it seems to be working with Redmine 3.2. But then I noticed that the users page ist no longer working. 

If I uninstall the wiking plugin again the users page is working.

Here a part of the log file:
Started GET "/users/pwe" for 192.168.90.198 at 2016-02-01 12:13:38 +0000
Processing by UsersController#show as HTML
  Parameters: {"id"=>"pwe"}
  Current user: pwe (id=11)
  Rendered plugins/wiking/app/views/wiking/_mentions.html.erb (1.7ms)
  Rendered users/show.html.erb within layouts/base (45.5ms)
Completed 500 Internal Server Error in 80ms (ActiveRecord: 13.5ms)

ActiveRecord::RecordNotFound (Couldn't find all Mentions with 'id': (all, {:conditions=>{:mentioned_id=>11}, :order=>"created_on DESC"}) (found 0 results, but was looking for 2)):
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in`map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/users/show.html.erb:78:in`_app_views_users_show_html_erb__2582475820153512047_70251987444060'
  app/controllers/users_controller.rb:77:in `block (2 levels) in show'
  app/controllers/users_controller.rb:73:in`show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by martin-denizet** [comment]
I see. I will check it out.

**Comment by martin-denizet** [comment]
Better late than never. It took me some time to understand, I actually already fixed that issue and pushed it to develop and tag 1.1.1 but somehow I missed pushing the updated master branch!
Sorry for that!
